
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: onbooking
  username: postgres
  password: 2040

test:
  <<: *default
  database: onbooking
  username: postgres
  password: 2040
production:
  <<: *default
  database:   url: <%= ENV['DATABASE_URL'] %>