
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onbooking_dev
  username: postgres
  password: 2040

test:
  <<: *default
  database: onbooking_test
  username: postgres
  password: 2040

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>